window.ESPORTS_DATA = {
  "updatedAt": "2026-10-07T10:11:45.152Z",
  "sourceLabel": "LoL Esports",
  "dataMode": "live-refresh",
  "autoUpdated": true,
  "sourceUrl": "https://lolesports.com/en-US",
  "worlds": {
    "status": "UPCOMING",
    "start": "2026-10-15",
    "end": "2026-11-14",
    "teamsKnown": [
      "HLE",
      "GEN",
      "BLG",
      "G2",
      "T1",
      "LYON",
      "DK",
      "AL",
      "KC",
      "CFO",
      "MVK",
      "TSW"
    ]
  },
  "rankings": [
    {
      "rank": 1,
      "code": "HLE",
      "name": "Hanwha Life Esports",
      "league": "LCK",
      "score": 1540,
      "record": "28-13"
    },
    {
      "rank": 2,
      "code": "GEN",
      "name": "Gen.G Esports",
      "league": "LCK",
      "score": 1519,
      "record": "33-9"
    },
    {
      "rank": 3,
      "code": "BLG",
      "name": "BILIBILI GAMING",
      "league": "LPL",
      "score": 1513,
      "record": "48-11"
    },
    {
      "rank": 4,
      "code": "G2",
      "name": "G2 Esports",
      "league": "LEC",
      "score": 1475,
      "record": "33-15"
    },
    {
      "rank": 5,
      "code": "T1",
      "name": "T1",
      "league": "LCK",
      "score": 1471,
      "record": "29-16"
    },
    {
      "rank": 6,
      "code": "LYON",
      "name": "LYON",
      "league": "LCS",
      "score": 1443,
      "record": "24-10"
    },
    {
      "rank": 7,
      "code": "DK",
      "name": "Dplus KIA",
      "league": "LCK",
      "score": 1409,
      "record": "27-16"
    },
    {
      "rank": 7,
      "code": "AL",
      "name": "Anyone's Legend",
      "league": "LPL",
      "score": 1409,
      "record": "32-18"
    }
  ],
  "schedule": [
    {
      "eventId": "",
      "startTime": "2026-10-07T07:00:00Z",
      "league": "DCGI",
      "leagueCode": "demacia_cup",
      "stage": "Swiss",
      "a": "FlyQuest",
      "aCode": "FLY",
      "b": "GAM Esports",
      "bCode": "GAM",
      "status": "COMPLETED",
      "strategy": "bestOf",
      "count": 3
    },
    {
      "eventId": "",
      "startTime": "2026-10-07T09:00:00Z",
      "league": "DCGI",
      "leagueCode": "demacia_cup",
      "stage": "Swiss",
      "a": "GAM Esports",
      "aCode": "GAM",
      "b": "Shopify Rebellion",
      "bCode": "SR",
      "status": "COMPLETED",
      "strategy": "bestOf",
      "count": 3
    },
    {
      "eventId": "",
      "startTime": "2026-10-07T11:00:00Z",
      "league": "DCGI",
      "leagueCode": "demacia_cup",
      "stage": "Swiss",
      "a": "FlyQuest",
      "aCode": "FLY",
      "b": "Shopify Rebellion",
      "bCode": "SR",
      "status": "INPROGRESS",
      "strategy": "bestOf",
      "count": 3
    },
    {
      "eventId": "",
      "startTime": "2026-10-07T16:00:00Z",
      "league": "EMEA Masters",
      "leagueCode": "emea_masters",
      "stage": "Playoffs",
      "a": "Heretics Academy",
      "aCode": "HRTS",
      "b": "G2 NORD",
      "bCode": "G2N",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    },
    {
      "eventId": "",
      "startTime": "2026-10-07T16:00:00Z",
      "league": "EMEA Masters",
      "leagueCode": "emea_masters",
      "stage": "Playoffs",
      "a": "Karmine Corp Blue",
      "aCode": "KCB",
      "b": "Skillcamp",
      "bCode": "SC",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    },
    {
      "eventId": "",
      "startTime": "2026-10-07T16:00:00Z",
      "league": "EMEA Masters",
      "leagueCode": "emea_masters",
      "stage": "Playoffs",
      "a": "Anubis Gaming",
      "aCode": "ANB",
      "b": "Ruddy Corporation",
      "bCode": "RUD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    },
    {
      "eventId": "",
      "startTime": "2026-10-07T16:00:00Z",
      "league": "EMEA Masters",
      "leagueCode": "emea_masters",
      "stage": "Playoffs",
      "a": "Kaufland Hangry Knights",
      "aCode": "KHK",
      "b": "Unicorns of Love Sexy Edition",
      "bCode": "USE",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    },
    {
      "eventId": "",
      "startTime": "2026-10-07T21:00:00Z",
      "league": "LCS Promotion",
      "leagueCode": "lcs_promotion",
      "stage": "Regional Qualifier",
      "a": "Maryville University",
      "aCode": "MU",
      "b": "Disguised",
      "bCode": "DSG",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    },
    {
      "eventId": "",
      "startTime": "2026-10-08T09:00:00Z",
      "league": "DCGI",
      "leagueCode": "demacia_cup",
      "stage": "Swiss",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 3
    },
    {
      "eventId": "",
      "startTime": "2026-10-08T11:00:00Z",
      "league": "DCGI",
      "leagueCode": "demacia_cup",
      "stage": "Swiss",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 3
    },
    {
      "eventId": "",
      "startTime": "2026-10-08T21:00:00Z",
      "league": "LCS Promotion",
      "leagueCode": "lcs_promotion",
      "stage": "Regional Qualifier",
      "a": "TBD",
      "aCode": "TBD",
      "b": "Cupid Esports",
      "bCode": "CPD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    },
    {
      "eventId": "",
      "startTime": "2026-10-09T16:00:00Z",
      "league": "EMEA Masters",
      "leagueCode": "emea_masters",
      "stage": "Playoffs",
      "a": "TLN Pirates",
      "aCode": "TLNP",
      "b": "Movistar KOI Fénix",
      "bCode": "MKF",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    },
    {
      "eventId": "",
      "startTime": "2026-10-09T16:00:00Z",
      "league": "EMEA Masters",
      "leagueCode": "emea_masters",
      "stage": "Playoffs",
      "a": "TBD",
      "aCode": "TBD",
      "b": "Galions",
      "bCode": "GL",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    },
    {
      "eventId": "",
      "startTime": "2026-10-09T21:00:00Z",
      "league": "LCS Promotion",
      "leagueCode": "lcs_promotion",
      "stage": "Regional Qualifier",
      "a": "TBD",
      "aCode": "TBD",
      "b": "FUEGO",
      "bCode": "FUE",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    },
    {
      "eventId": "",
      "startTime": "2026-10-10T16:00:00Z",
      "league": "EMEA Masters",
      "leagueCode": "emea_masters",
      "stage": "Playoffs",
      "a": "TBD",
      "aCode": "TBD",
      "b": "Solary",
      "bCode": "SLY",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    },
    {
      "eventId": "",
      "startTime": "2026-10-10T16:00:00Z",
      "league": "EMEA Masters",
      "leagueCode": "emea_masters",
      "stage": "Playoffs",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    },
    {
      "eventId": "",
      "startTime": "2026-10-10T16:00:00Z",
      "league": "CBLOL",
      "leagueCode": "cblol-brazil",
      "stage": "Finals",
      "a": "FURIA",
      "aCode": "FUR",
      "b": "LOS",
      "bCode": "LOS",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    },
    {
      "eventId": "",
      "startTime": "2026-10-10T21:00:00Z",
      "league": "LCS Promotion",
      "leagueCode": "lcs_promotion",
      "stage": "Regional Qualifier",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    },
    {
      "eventId": "",
      "startTime": "2026-10-11T10:00:00Z",
      "league": "VCS",
      "leagueCode": "vcs",
      "stage": "Finals",
      "a": "Saigon MVKE Academy",
      "aCode": "MVKA",
      "b": "Saigon Warrior",
      "bCode": "SGW",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    },
    {
      "eventId": "",
      "startTime": "2026-10-12T06:00:00Z",
      "league": "DCGI",
      "leagueCode": "demacia_cup",
      "stage": "Quarterfinals",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    },
    {
      "eventId": "",
      "startTime": "2026-10-12T09:00:00Z",
      "league": "DCGI",
      "leagueCode": "demacia_cup",
      "stage": "Quarterfinals",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    },
    {
      "eventId": "",
      "startTime": "2026-10-12T21:00:00Z",
      "league": "CBLOL Promotion",
      "leagueCode": "cblol_promotion",
      "stage": "Finals",
      "a": "KaBuM! Eports",
      "aCode": "KBM",
      "b": "LOS",
      "bCode": "LOS",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    },
    {
      "eventId": "",
      "startTime": "2026-10-12T23:00:00Z",
      "league": "LCS Promotion",
      "leagueCode": "lcs_promotion",
      "stage": "Finals",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    },
    {
      "eventId": "",
      "startTime": "2026-10-13T06:00:00Z",
      "league": "DCGI",
      "leagueCode": "demacia_cup",
      "stage": "Quarterfinals",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    },
    {
      "eventId": "",
      "startTime": "2026-10-13T09:00:00Z",
      "league": "DCGI",
      "leagueCode": "demacia_cup",
      "stage": "Quarterfinals",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    },
    {
      "eventId": "",
      "startTime": "2026-10-13T16:00:00Z",
      "league": "EMEA Masters",
      "leagueCode": "emea_masters",
      "stage": "Playoffs",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    },
    {
      "eventId": "",
      "startTime": "2026-10-14T09:00:00Z",
      "league": "DCGI",
      "leagueCode": "demacia_cup",
      "stage": "Semifinals",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    },
    {
      "eventId": "",
      "startTime": "2026-10-14T16:00:00Z",
      "league": "EMEA Masters",
      "leagueCode": "emea_masters",
      "stage": "Playoffs",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    },
    {
      "eventId": "",
      "startTime": "2026-10-15T09:00:00Z",
      "league": "DCGI",
      "leagueCode": "demacia_cup",
      "stage": "Semifinals",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    },
    {
      "eventId": "",
      "startTime": "2026-10-15T18:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Play-Ins",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    },
    {
      "eventId": "",
      "startTime": "2026-10-15T23:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Play-Ins",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    },
    {
      "eventId": "",
      "startTime": "2026-10-16T18:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Play-Ins",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    },
    {
      "eventId": "",
      "startTime": "2026-10-16T23:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Play-Ins",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    },
    {
      "eventId": "",
      "startTime": "2026-10-17T09:00:00Z",
      "league": "DCGI",
      "leagueCode": "demacia_cup",
      "stage": "Finals",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    },
    {
      "eventId": "",
      "startTime": "2026-10-17T18:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Play-Ins",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    },
    {
      "eventId": "",
      "startTime": "2026-10-18T18:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Play-Ins",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    },
    {
      "eventId": "",
      "startTime": "2026-10-23T16:00:00Z",
      "league": "EMEA Masters",
      "leagueCode": "emea_masters",
      "stage": "Finals",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    },
    {
      "eventId": "",
      "startTime": "2026-10-23T17:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Swiss",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 1
    },
    {
      "eventId": "",
      "startTime": "2026-10-23T18:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Swiss",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 1
    },
    {
      "eventId": "",
      "startTime": "2026-10-23T19:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Swiss",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 1
    },
    {
      "eventId": "",
      "startTime": "2026-10-23T20:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Swiss",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 1
    },
    {
      "eventId": "",
      "startTime": "2026-10-23T21:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Swiss",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 1
    },
    {
      "eventId": "",
      "startTime": "2026-10-23T22:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Swiss",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 1
    },
    {
      "eventId": "",
      "startTime": "2026-10-23T23:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Swiss",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 1
    },
    {
      "eventId": "",
      "startTime": "2026-10-24T00:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Swiss",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 1
    },
    {
      "eventId": "",
      "startTime": "2026-10-24T17:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Swiss",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 1
    },
    {
      "eventId": "",
      "startTime": "2026-10-24T18:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Swiss",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 1
    },
    {
      "eventId": "",
      "startTime": "2026-10-24T19:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Swiss",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 1
    },
    {
      "eventId": "",
      "startTime": "2026-10-24T20:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Swiss",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 1
    },
    {
      "eventId": "",
      "startTime": "2026-10-24T21:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Swiss",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 1
    },
    {
      "eventId": "",
      "startTime": "2026-10-24T22:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Swiss",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 1
    },
    {
      "eventId": "",
      "startTime": "2026-10-24T23:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Swiss",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 1
    },
    {
      "eventId": "",
      "startTime": "2026-10-25T00:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Swiss",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 1
    },
    {
      "eventId": "",
      "startTime": "2026-10-25T17:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Swiss",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 1
    },
    {
      "eventId": "",
      "startTime": "2026-10-25T18:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Swiss",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 1
    },
    {
      "eventId": "",
      "startTime": "2026-10-25T19:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Swiss",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 3
    },
    {
      "eventId": "",
      "startTime": "2026-10-25T22:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Swiss",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 3
    },
    {
      "eventId": "",
      "startTime": "2026-10-26T17:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Swiss",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 1
    },
    {
      "eventId": "",
      "startTime": "2026-10-26T18:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Swiss",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 1
    },
    {
      "eventId": "",
      "startTime": "2026-10-26T19:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Swiss",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 3
    },
    {
      "eventId": "",
      "startTime": "2026-10-26T22:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Swiss",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 3
    },
    {
      "eventId": "",
      "startTime": "2026-10-28T20:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Swiss",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 3
    },
    {
      "eventId": "",
      "startTime": "2026-10-28T23:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Swiss",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 3
    },
    {
      "eventId": "",
      "startTime": "2026-10-29T20:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Swiss",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 3
    },
    {
      "eventId": "",
      "startTime": "2026-10-29T23:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Swiss",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 3
    },
    {
      "eventId": "",
      "startTime": "2026-10-30T20:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Swiss",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 3
    },
    {
      "eventId": "",
      "startTime": "2026-10-30T23:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Swiss",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 3
    },
    {
      "eventId": "",
      "startTime": "2026-10-31T17:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Swiss",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 3
    },
    {
      "eventId": "",
      "startTime": "2026-10-31T20:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Swiss",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 3
    },
    {
      "eventId": "",
      "startTime": "2026-10-31T23:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Swiss",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 3
    },
    {
      "eventId": "",
      "startTime": "2026-11-03T22:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Quarterfinals",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    },
    {
      "eventId": "",
      "startTime": "2026-11-04T22:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Quarterfinals",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    },
    {
      "eventId": "",
      "startTime": "2026-11-05T22:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Quarterfinals",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    },
    {
      "eventId": "",
      "startTime": "2026-11-06T22:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Quarterfinals",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    },
    {
      "eventId": "",
      "startTime": "2026-11-07T22:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Semifinals",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    },
    {
      "eventId": "",
      "startTime": "2026-11-08T22:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Semifinals",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    },
    {
      "eventId": "",
      "startTime": "2026-11-14T19:00:00Z",
      "league": "Worlds",
      "leagueCode": "worlds",
      "stage": "Finals",
      "a": "TBD",
      "aCode": "TBD",
      "b": "TBD",
      "bCode": "TBD",
      "status": "UNSTARTED",
      "strategy": "bestOf",
      "count": 5
    }
  ],
  "players": [
    {
      "id": "doran",
      "role": "TOP",
      "name": "Doran",
      "team": "T1",
      "rank": 1,
      "projection": 24.4,
      "verified": true
    },
    {
      "id": "oner",
      "role": "JNG",
      "name": "Oner",
      "team": "T1",
      "rank": 2,
      "projection": 26.7,
      "verified": true
    },
    {
      "id": "faker",
      "role": "MID",
      "name": "Faker",
      "team": "T1",
      "rank": 3,
      "projection": 28.6,
      "verified": true
    },
    {
      "id": "peyz",
      "role": "ADC",
      "name": "Peyz",
      "team": "T1",
      "rank": 4,
      "projection": 29.7,
      "verified": true
    },
    {
      "id": "keria",
      "role": "SUP",
      "name": "Keria",
      "team": "T1",
      "rank": 5,
      "projection": 22.8,
      "verified": true
    },
    {
      "id": "kiin",
      "role": "TOP",
      "name": "Kiin",
      "team": "Gen.G Esports",
      "rank": 6,
      "projection": 25,
      "verified": true
    },
    {
      "id": "canyon",
      "role": "JNG",
      "name": "Canyon",
      "team": "Gen.G Esports",
      "rank": 7,
      "projection": 31.2,
      "verified": true
    },
    {
      "id": "chovy",
      "role": "MID",
      "name": "Chovy",
      "team": "Gen.G Esports",
      "rank": 8,
      "projection": 36.7,
      "verified": true
    },
    {
      "id": "ruler",
      "role": "ADC",
      "name": "Ruler",
      "team": "Gen.G Esports",
      "rank": 9,
      "projection": 30.1,
      "verified": true
    },
    {
      "id": "duro",
      "role": "SUP",
      "name": "Duro",
      "team": "Gen.G Esports",
      "rank": 10,
      "projection": 19.8,
      "verified": true
    },
    {
      "id": "zamudo",
      "role": "TOP",
      "name": "Zamudo",
      "team": "LYON",
      "rank": 11,
      "projection": 21.1,
      "verified": true
    },
    {
      "id": "inspired",
      "role": "JNG",
      "name": "Inspired",
      "team": "LYON",
      "rank": 12,
      "projection": 25.1,
      "verified": true
    },
    {
      "id": "saint",
      "role": "MID",
      "name": "Saint",
      "team": "LYON",
      "rank": 13,
      "projection": 22.7,
      "verified": true
    },
    {
      "id": "berserker",
      "role": "ADC",
      "name": "Berserker",
      "team": "LYON",
      "rank": 14,
      "projection": 25.5,
      "verified": true
    },
    {
      "id": "isles",
      "role": "SUP",
      "name": "Isles",
      "team": "LYON",
      "rank": 15,
      "projection": 18.3,
      "verified": true
    },
    {
      "id": "gakgos",
      "role": "TOP",
      "name": "Gakgos",
      "team": "FlyQuest",
      "rank": 16,
      "projection": 20.9,
      "verified": true
    },
    {
      "id": "gryffinn",
      "role": "JNG",
      "name": "Gryffinn",
      "team": "FlyQuest",
      "rank": 17,
      "projection": 22.4,
      "verified": true
    },
    {
      "id": "quad",
      "role": "MID",
      "name": "Quad",
      "team": "FlyQuest",
      "rank": 18,
      "projection": 23.3,
      "verified": true
    },
    {
      "id": "massu",
      "role": "ADC",
      "name": "Massu",
      "team": "FlyQuest",
      "rank": 19,
      "projection": 24.3,
      "verified": true
    },
    {
      "id": "cryogen",
      "role": "SUP",
      "name": "Cryogen",
      "team": "FlyQuest",
      "rank": 20,
      "projection": 17.9,
      "verified": true
    },
    {
      "id": "impact",
      "role": "TOP",
      "name": "Impact",
      "team": "Sentinels",
      "rank": 21,
      "projection": 20.7,
      "verified": true
    },
    {
      "id": "hambak",
      "role": "JNG",
      "name": "HamBak",
      "team": "Sentinels",
      "rank": 22,
      "projection": 21.8,
      "verified": true
    },
    {
      "id": "darkwings",
      "role": "MID",
      "name": "DARKWINGS",
      "team": "Sentinels",
      "rank": 23,
      "projection": 21.4,
      "verified": true
    },
    {
      "id": "rahel",
      "role": "ADC",
      "name": "Rahel",
      "team": "Sentinels",
      "rank": 24,
      "projection": 22.8,
      "verified": true
    },
    {
      "id": "huhi",
      "role": "SUP",
      "name": "huhi",
      "team": "Sentinels",
      "rank": 25,
      "projection": 17.5,
      "verified": true
    }
  ],
  "leagues": [
    {
      "id": "98767975604431411",
      "name": "Worlds",
      "slug": "worlds",
      "region": "INTERNATIONAL"
    },
    {
      "id": "98767991325878492",
      "name": "MSI",
      "slug": "msi",
      "region": "INTERNATIONAL"
    },
    {
      "id": "98767991299243165",
      "name": "LCS",
      "slug": "lcs",
      "region": "NORTH AMERICA"
    },
    {
      "id": "98767991332355509",
      "name": "CBLOL",
      "slug": "cblol-brazil",
      "region": "BRAZIL"
    },
    {
      "id": "117370069134032321",
      "name": "LCS Promotion",
      "slug": "lcs_promotion",
      "region": "NORTH AMERICA"
    },
    {
      "id": "117370077081924460",
      "name": "CBLOL Promotion",
      "slug": "cblol_promotion",
      "region": "BRAZIL"
    },
    {
      "id": "98767991302996019",
      "name": "LEC",
      "slug": "lec",
      "region": "EMEA"
    },
    {
      "id": "98767991310872058",
      "name": "LCK",
      "slug": "lck",
      "region": "KOREA"
    },
    {
      "id": "98767991314006698",
      "name": "LPL",
      "slug": "lpl",
      "region": "CHINA"
    },
    {
      "id": "98767991349978712",
      "name": "LJL",
      "slug": "ljl-japan",
      "region": "JAPAN"
    },
    {
      "id": "98767991335774713",
      "name": "LCK Challengers",
      "slug": "lck_challengers_league",
      "region": "KOREA"
    },
    {
      "id": "104366947889790212",
      "name": "PCS",
      "slug": "pcs",
      "region": "HONG KONG, MACAU, TAIWAN"
    },
    {
      "id": "107213827295848783",
      "name": "VCS",
      "slug": "vcs",
      "region": "VIETNAM"
    },
    {
      "id": "113475149040947852",
      "name": "LTA Cross-Conference",
      "slug": "lta_cross",
      "region": "AMERICAS"
    },
    {
      "id": "110988878756156222",
      "name": "Worlds Qualifying Series",
      "slug": "wqs",
      "region": "INTERNATIONAL"
    },
    {
      "id": "113470291645289904",
      "name": "LTA North",
      "slug": "lta_n",
      "region": "AMERICAS"
    },
    {
      "id": "113475181634818701",
      "name": "LTA South",
      "slug": "lta_s",
      "region": "AMERICAS"
    }
  ]
};
